version: '3.3'

networks:
  inception:

services:
  nginx:
    build: requirements/nginx/.
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    env_file:
      - .env
    restart: always

  wordpress:
    build: requirements/wordpress/.
    container_name: wp-php
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    env_file:
      - .env
    restart: always

  mariadb:
    build: requirements/mariadb/.
    container_name: mariadb
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception
    env_file:
      - .env
    restart: always

volumes:
  wordpress:
  mariadb:
