version: "3.8"

networks:
  inception:
      driver: bridge

volumes:
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      device: /home/yu-chen/data/wordpress
      type: none
      o: bind
  mariadb:
    #name: mariadb
    driver: local
    driver_opts:
      device: /home/yu-chen/data/mariadb
      type: none
      o: bind

services:
  nginx:
    build: requirements/nginx/.
    container_name: nginx
    #image: nginx 
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    env_file:
      - .env
    restart: always

  wordpress:
    build: requirements/wordpress/.
    container_name: wordpress
    #image: wordpress
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    env_file:
      - .env
    restart: always

  mariadb:
    build: requirements/mariadb/.
    container_name: mariadb
    image: mariadb
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception
    env_file:
      - .env
    restart: always