FROM debian:latest

RUN apt update && apt upgrade && apt install -y mariadb-server
RUN echo 'root:vagrant' | chpasswd

COPY 50-server.cnf /etc/mysql/mariadb.conf.d/.
COPY init.sql /etc/mysql/init.sql

RUN mkdir /run/mysqld

CMD ["mysqld"]