version: '3.9'


services:
  nginx:
    build: requirements/nginx
    ports:
      - "443:443"
    networks:
      - inception_network

  wordpress:
    build: requirements/wordpress
    networks:
      - inception_network
    depends_on:
      - mariadb
    volumes:
      - wordpress_files:/var/www/wordpress

  mariadb:
    build: requirements/mariadb
    networks:
      - inception_network
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql

networks:
  inception_network:
volumes:
  db_data:
  wordpress_files: